import type { Scenario } from "../../types/pipeline.types";

export const sampleScenario: Scenario = {
  id: "scenario_default",
  code: "basic_recognition_blank",
  name: "Базовое распознавание",
  description: "Базовый пайплайн распознавания и отчета",
  isActive: true,
  allowedRoles: ["ADMIN", "VIEWER"],
  instructionTypes: ["intro"],
  config: {
    edgeRenderMode: "orthogonal",
  },
  steps: [
    {
      id: "step_audio_source",
      scenarioId: "scenario_default",
      moduleId: "AUDIO_FROM_UPLOAD",
      code: "step_1",
      orderHint: 1,
      config: {
        localUrl: "",
        layout: { x: 40, y: 120 },
      },
      produces: ["AUDIO"],
      requires: ["AUDIO_SOURCE"],
    },
    {
      id: "step_audio_prepare",
      scenarioId: "scenario_default",
      moduleId: "AUDIO_PREPARE",
      code: "step_2",
      orderHint: 2,
      config: {
        targetSampleRate: 16000,
        targetChannels: 1,
        chunkSec: 120,
        overlapSec: 1,
        layout: { x: 360, y: 80 },
      },
      produces: ["AUDIO_PREPARED"],
      requires: ["AUDIO"],
    },
    {
      id: "step_asr",
      scenarioId: "scenario_default",
      moduleId: "ASR",
      code: "step_3",
      orderHint: 3,
      config: {
        whisperModel: "small",
        asrDevice: "auto",
        asrComputeType: "int8",
        layout: { x: 680, y: 120 },
      },
      produces: ["TEXT"],
      requires: ["AUDIO_PREPARED", "AUDIO"],
    },
    {
      id: "step_report",
      scenarioId: "scenario_default",
      moduleId: "REPORT_OUTPUT",
      code: "step_4",
      orderHint: 4,
      config: {
        sections: {
          summary: false,
          transcript: true,
          psych: false,
          checklist: false,
        },
        strict: false,
        layout: { x: 1000, y: 120 },
      },
      produces: ["SESSION_REPORT"],
      requires: [],
    },
  ],
  edges: [
    {
      id: "edge_source_to_asr",
      scenarioId: "scenario_default",
      fromStepId: "step_audio_source",
      toStepId: "step_audio_prepare",
      artifactTypeId: "AUDIO",
    },
    {
      id: "edge_prepared_to_asr",
      scenarioId: "scenario_default",
      fromStepId: "step_audio_prepare",
      toStepId: "step_asr",
      artifactTypeId: "AUDIO_PREPARED",
    },
    {
      id: "edge_source_to_prepare",
      scenarioId: "scenario_default",
      fromStepId: "step_audio_source",
      toStepId: "step_asr",
      artifactTypeId: "AUDIO",
    },
    {
      id: "edge_asr_to_report",
      scenarioId: "scenario_default",
      fromStepId: "step_asr",
      toStepId: "step_report",
      artifactTypeId: "TEXT",
    },
  ],
};
